---
apiVersion: v1
kind: Secret
metadata:
  name: danieloh30-danieloh30-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rosa916-rvhvd/danieloh30-gateway-gitops
